{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Sets the patient ID for the current test session.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdots\/mainviewcontroller\/setpatientid(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdots\/mainviewcontroller\/setpatientid(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setPatientID(_:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPatientID","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"patientId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"patientId","content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier for the patient.","type":"text"}]},{"type":"codeListing","syntax":"objc","code":["[mainViewController setPatientID:@\"12345\"];"]}]}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setPatientID:"}],"title":"setPatientID(_:)","modules":[{"name":"MDots"}],"externalID":"c:objc(cs)MainViewController(im)setPatientID:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPatientID"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController"]]},"kind":"symbol","references":{"doc://com.estelapasjak.Mdots/documentation/MDots":{"type":"topic","role":"collection","url":"\/documentation\/mdots","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","abstract":[],"images":[{"identifier":"appIcon.png","type":"icon"}],"kind":"symbol","title":"MDots"},"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController","title":"MainViewController","role":"symbol","url":"\/documentation\/mdots\/mainviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainViewController"}],"navigatorTitle":[{"kind":"identifier","text":"MainViewController"}],"type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController/setPatientID(_:)":{"title":"setPatientID(_:)","role":"symbol","navigatorTitle":[{"text":"setPatientID:","kind":"identifier"}],"abstract":[{"type":"text","text":"Sets the patient ID for the current test session."}],"url":"\/documentation\/mdots\/mainviewcontroller\/setpatientid(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPatientID","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setPatientID(_:)"},"appIcon.png":{"alt":"The logo representing the MDot sensor application.","identifier":"appIcon.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/appIcon.png"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setPatientID:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPatientID:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setPatientID:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"patientId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"MainViewController","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController\/title"},{"value":[{"text":"MainViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController\/fragments"},{"value":"setPatientID:","op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setPatientID(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setPatientID:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setPatientID(_:)\/fragments"}]}]}