{"variants":[{"paths":["\/documentation\/mdots\/mainviewcontroller\/setside(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdots\/mainviewcontroller\/setside(_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSide","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"side","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The side of the body to be tested (e.g., left, right)."}],"type":"paragraph"},{"code":["[mainViewController setSide:@\"L\"];"],"syntax":"objc","type":"codeListing"}],"name":"side"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController"]]},"kind":"symbol","metadata":{"title":"setSide(_:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"setSide:"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSide","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"MDots"}],"externalID":"c:objc(cs)MainViewController(im)setSide:"},"abstract":[{"text":"Sets the side (left, right, single,e tc) for the test.","type":"text"}],"identifier":{"url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setSide(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController":{"role":"symbol","url":"\/documentation\/mdots\/mainviewcontroller","title":"MainViewController","navigatorTitle":[{"kind":"identifier","text":"MainViewController"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MainViewController","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController"},"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController/setSide(_:)":{"navigatorTitle":[{"text":"setSide:","kind":"identifier"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setSide(_:)","role":"symbol","url":"\/documentation\/mdots\/mainviewcontroller\/setside(_:)","type":"topic","kind":"symbol","abstract":[{"text":"Sets the side (left, right, single,e tc) for the test.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setSide"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setSide(_:)"},"new-icon.png":{"variants":[{"url":"\/images\/new-icon.png","traits":["1x","light"]}],"identifier":"new-icon.png","alt":"The logo representing the MDot sensor application.","type":"image"},"doc://com.estelapasjak.Mdots/documentation/MDots":{"url":"\/documentation\/mdots","kind":"symbol","abstract":[],"role":"collection","images":[{"type":"icon","identifier":"new-icon.png"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","type":"topic","title":"MDots"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"setSide:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setSide:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setSide:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"side"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController\/title","value":"MainViewController"},{"op":"replace","value":[{"text":"MainViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController\/fragments"},{"value":"setSide:","op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setSide(_:)\/title"},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setSide(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setSide:","kind":"identifier"}]}]}]}