{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setSide","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"side"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mdots\/measureviewcontroller\/setside(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdots\/measureviewcontroller\/setside(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController"]]},"metadata":{"modules":[{"name":"MDots"}],"externalID":"c:objc(cs)MeasureViewController(im)setSide:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setSide","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Instance Method","title":"setSide(_:)","symbolKind":"method","navigatorTitle":[{"text":"setSide:","kind":"identifier"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setSide(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.estelapasjak.Mdots/documentation/MDots":{"kind":"symbol","role":"collection","title":"MDots","url":"\/documentation\/mdots","type":"topic","abstract":[],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots"},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController/setSide(_:)":{"url":"\/documentation\/mdots\/measureviewcontroller\/setside(_:)","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setSide(_:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setSide","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"setSide(_:)","navigatorTitle":[{"text":"setSide:","kind":"identifier"}],"type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController":{"navigatorTitle":[{"kind":"identifier","text":"MeasureViewController"}],"kind":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController","title":"MeasureViewController","abstract":[],"url":"\/documentation\/mdots\/measureviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MeasureViewController"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setSide:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setSide:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setSide:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"side"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"setSide:","op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setSide(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSide:"}],"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setSide(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/title","value":"MeasureViewController"},{"value":[{"kind":"identifier","text":"MeasureViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}