{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setTestType(_:)"},"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)MeasureViewController(im)setTestType:","title":"setTestType(_:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setTestType","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"modules":[{"name":"MDots"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setTestType:"}]},"variants":[{"paths":["\/documentation\/mdots\/measureviewcontroller\/settesttype(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdots\/measureviewcontroller\/settesttype(_:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTestType"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"testtype"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController":{"navigatorTitle":[{"kind":"identifier","text":"MeasureViewController"}],"kind":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController","title":"MeasureViewController","abstract":[],"url":"\/documentation\/mdots\/measureviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MeasureViewController"}],"type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController/setTestType(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setTestType:"}],"kind":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setTestType(_:)","title":"setTestType(_:)","abstract":[],"url":"\/documentation\/mdots\/measureviewcontroller\/settesttype(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setTestType","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots":{"kind":"symbol","role":"collection","title":"MDots","url":"\/documentation\/mdots","type":"topic","abstract":[],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"setTestType:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTestType:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setTestType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"testtype"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"MeasureViewController","op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/title"},{"value":[{"kind":"identifier","text":"MeasureViewController"}],"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setTestType(_:)\/title","value":"setTestType:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setTestType:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setTestType(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}