{"sections":[],"identifier":{"url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.estelapasjak.Mdots\/objc(cs)UIViewController"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSCoding","doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSObject","doc:\/\/com.estelapasjak.Mdots\/s7CVarArgP","doc:\/\/com.estelapasjak.Mdots\/s28CustomDebugStringConvertibleP","doc:\/\/com.estelapasjak.Mdots\/s23CustomStringConvertibleP","doc:\/\/com.estelapasjak.Mdots\/SQ","doc:\/\/com.estelapasjak.Mdots\/SH","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIAppearanceContainer","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIContentContainer","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIFocusEnvironment","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIStateRestoring","doc:\/\/com.estelapasjak.Mdots\/5UIKit23UITraitChangeObservableP","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UITraitEnvironment","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIUserActivityRestoring","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UITraitChangeObservable"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MainViewController"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdots\/mainviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdots\/mainviewcontroller"]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setPatientID(_:)","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setSide(_:)","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setTestType(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:objc(cs)MainViewController","title":"MainViewController","roleHeading":"Class","role":"symbol","modules":[{"name":"MDots"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MainViewController","kind":"identifier"}],"navigatorTitle":[{"text":"MainViewController","kind":"identifier"}],"symbolKind":"class"},"references":{"doc://com.estelapasjak.Mdots/objc(cs)UIViewController":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(cs)UIViewController","title":"UIViewController","type":"unresolvable"},"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController/setTestType(_:)":{"title":"setTestType(_:)","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setTestType(_:)","url":"\/documentation\/mdots\/mainviewcontroller\/settesttype(_:)","kind":"symbol","navigatorTitle":[{"text":"setTestType:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Sets the type of test to be conducted.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTestType","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController","title":"MainViewController","role":"symbol","url":"\/documentation\/mdots\/mainviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainViewController"}],"navigatorTitle":[{"kind":"identifier","text":"MainViewController"}],"type":"topic"},"doc://com.estelapasjak.Mdots/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.estelapasjak.Mdots/documentation/MDots":{"type":"topic","role":"collection","url":"\/documentation\/mdots","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","abstract":[],"images":[{"identifier":"appIcon.png","type":"icon"}],"kind":"symbol","title":"MDots"},"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController/setPatientID(_:)":{"title":"setPatientID(_:)","role":"symbol","navigatorTitle":[{"text":"setPatientID:","kind":"identifier"}],"abstract":[{"type":"text","text":"Sets the patient ID for the current test session."}],"url":"\/documentation\/mdots\/mainviewcontroller\/setpatientid(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPatientID","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setPatientID(_:)"},"doc://com.estelapasjak.Mdots/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.estelapasjak.Mdots/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://com.estelapasjak.Mdots/objc(pl)UIContentContainer":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://com.estelapasjak.Mdots/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://com.estelapasjak.Mdots/objc(pl)UITraitChangeObservable":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UITraitChangeObservable","title":"UIKit.__UITraitChangeObservable","type":"unresolvable"},"doc://com.estelapasjak.Mdots/s7CVarArgP":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.estelapasjak.Mdots/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"appIcon.png":{"identifier":"appIcon.png","alt":"The logo representing the MDot sensor application.","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/appIcon.png"}]},"doc://com.estelapasjak.Mdots/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController/setSide(_:)":{"abstract":[{"type":"text","text":"Sets the side (left, right, single,e tc) for the test."}],"url":"\/documentation\/mdots\/mainviewcontroller\/setside(_:)","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setSide(_:)","role":"symbol","title":"setSide(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"setSide:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setSide"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://com.estelapasjak.Mdots/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.estelapasjak.Mdots/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.estelapasjak.Mdots/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.estelapasjak.Mdots/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.estelapasjak.Mdots/SQ":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.estelapasjak.Mdots/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://com.estelapasjak.Mdots/objc(pl)NSCoding":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://com.estelapasjak.Mdots/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.estelapasjak.Mdots/SH":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.estelapasjak.Mdots/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MainViewController","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"MainViewController","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MainViewController"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setPatientID(_:)","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setSide(_:)","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setTestType(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.estelapasjak.Mdots\/objc(cs)UIViewController"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}]}]}},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setTestType(_:)\/title","value":"setTestType:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"setTestType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setTestType(_:)\/fragments"},{"op":"replace","value":"MainViewController","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController\/fragments","value":[{"kind":"identifier","text":"MainViewController"}]},{"value":"setPatientID:","op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setPatientID(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPatientID:"}],"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setPatientID(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setSide(_:)\/title","value":"setSide:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setSide:"}],"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setSide(_:)\/fragments"}]}]}