{"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots"]]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.estelapasjak.Mdots\/objc(cs)UIViewController"],"kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSCoding","doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSObject","doc:\/\/com.estelapasjak.Mdots\/s7CVarArgP","doc:\/\/com.estelapasjak.Mdots\/s28CustomDebugStringConvertibleP","doc:\/\/com.estelapasjak.Mdots\/s23CustomStringConvertibleP","doc:\/\/com.estelapasjak.Mdots\/SQ","doc:\/\/com.estelapasjak.Mdots\/SH","doc:\/\/com.estelapasjak.Mdots\/s8SendableP","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIAppearanceContainer","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIContentContainer","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIFocusEnvironment","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIStateRestoring","doc:\/\/com.estelapasjak.Mdots\/5UIKit23UITraitChangeObservableP","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UITraitEnvironment","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIUserActivityRestoring","doc:\/\/com.estelapasjak.Mdots\/objc(pl)UITraitChangeObservable"],"kind":"relationships","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdots\/measureviewcontroller"]},{"paths":["\/documentation\/mdots\/measureviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"MDots"}],"externalID":"c:objc(cs)MeasureViewController","roleHeading":"Class","role":"symbol","title":"MeasureViewController","navigatorTitle":[{"kind":"identifier","text":"MeasureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MeasureViewController","kind":"identifier"}],"symbolKind":"class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MeasureViewController"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/measureDevices"]},{"identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setPatientID(_:)","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setSide(_:)","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setTestType(_:)"],"title":"Instance Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController"},"references":{"doc://com.estelapasjak.Mdots/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.estelapasjak.Mdots/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSExtensionRequestHandling"},"doc://com.estelapasjak.Mdots/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.estelapasjak.Mdots\/s8SendableP"},"doc://com.estelapasjak.Mdots/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(cs)UIViewController"},"doc://com.estelapasjak.Mdots/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIFocusEnvironment"},"doc://com.estelapasjak.Mdots/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIAppearanceContainer"},"new-icon.png":{"type":"image","variants":[{"url":"\/images\/new-icon.png","traits":["1x","light"]}],"alt":"The logo representing the MDot sensor application.","identifier":"new-icon.png"},"doc://com.estelapasjak.Mdots/objc(pl)UITraitChangeObservable":{"type":"unresolvable","title":"UIKit.__UITraitChangeObservable","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UITraitChangeObservable"},"doc://com.estelapasjak.Mdots/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.estelapasjak.Mdots/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.estelapasjak.Mdots\/s7CVarArgP"},"doc://com.estelapasjak.Mdots/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.estelapasjak.Mdots\/s23CustomStringConvertibleP"},"doc://com.estelapasjak.Mdots/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIUserActivityRestoring"},"doc://com.estelapasjak.Mdots/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIContentContainer"},"doc://com.estelapasjak.Mdots/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSObject"},"doc://com.estelapasjak.Mdots/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.estelapasjak.Mdots\/SH"},"doc://com.estelapasjak.Mdots/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)NSCoding"},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController/setSide(_:)":{"abstract":[{"text":"Sets the side (left, right, single, etc.) for the test.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setSide(_:)","url":"\/documentation\/mdots\/measureviewcontroller\/setside(_:)","role":"symbol","title":"setSide(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setSide","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setSide:","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController/setPatientID(_:)":{"title":"setPatientID(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPatientID","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the patient ID for the current test session."}],"url":"\/documentation\/mdots\/measureviewcontroller\/setpatientid(_:)","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setPatientID(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setPatientID:"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController/setTestType(_:)":{"type":"topic","abstract":[{"type":"text","text":"Sets the type of test to be conducted."}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setTestType(_:)","role":"symbol","navigatorTitle":[{"text":"setTestType:","kind":"identifier"}],"url":"\/documentation\/mdots\/measureviewcontroller\/settesttype(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTestType","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"setTestType(_:)","kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","title":"MDots","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/mdots","abstract":[],"images":[{"identifier":"new-icon.png","type":"icon"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController/measureDevices":{"abstract":[{"type":"text","text":"The measuring devices"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/measureDevices","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"measureDevices"}],"url":"\/documentation\/mdots\/measureviewcontroller\/measuredevices","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"measureDevices","kind":"identifier"},{"kind":"text","text":": ["},{"text":"DotDevice","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DotDevice"},{"text":"]","kind":"text"}],"title":"measureDevices","kind":"symbol"},"doc://com.estelapasjak.Mdots/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.estelapasjak.Mdots/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.estelapasjak.Mdots/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.estelapasjak.Mdots\/s28CustomDebugStringConvertibleP"},"doc://com.estelapasjak.Mdots/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.estelapasjak.Mdots\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.estelapasjak.Mdots/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.estelapasjak.Mdots\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://com.estelapasjak.Mdots/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.estelapasjak.Mdots\/SQ","title":"Swift.Equatable"},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController","url":"\/documentation\/mdots\/measureviewcontroller","role":"symbol","title":"MeasureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MeasureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"MeasureViewController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MeasureViewController","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MeasureViewController"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MeasureViewController"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/measureDevices"]},{"identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setPatientID(_:)","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setSide(_:)","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setTestType(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.estelapasjak.Mdots\/objc(cs)UIViewController"]}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MeasureViewController"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"setSide:","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setSide(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setSide:"}],"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setSide(_:)\/fragments","op":"replace"},{"op":"replace","value":"setPatientID:","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setPatientID(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPatientID:"}],"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setPatientID(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setTestType(_:)\/title","value":"setTestType:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTestType:"}],"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setTestType(_:)\/fragments"},{"op":"replace","value":"measureDevices","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1measureDevices\/title"},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1measureDevices\/fragments","op":"replace","value":[{"kind":"identifier","text":"measureDevices"}]},{"value":"MeasureViewController","op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/fragments","value":[{"kind":"identifier","text":"MeasureViewController"}]}]}]}