{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdots\/measureviewcontroller\/measuredevices"]},{"paths":["\/documentation\/mdots\/measureviewcontroller\/measuredevices"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The measureing devices","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"measureDevices","kind":"identifier"},{"kind":"text","text":": ["},{"text":"DotDevice","preciseIdentifier":"c:objc(cs)DotDevice","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"measureDevices"}],"externalID":"c:objc(cs)MeasureViewController(py)measureDevices","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"MDots"}],"title":"measureDevices","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"measureDevices"},{"text":": [","kind":"text"},{"text":"DotDevice","preciseIdentifier":"c:objc(cs)DotDevice","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"identifier":{"url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/measureDevices","interfaceLanguage":"swift"},"references":{"doc://com.estelapasjak.Mdots/documentation/MDots":{"type":"topic","url":"\/documentation\/mdots","title":"MDots","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","role":"collection"},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController/measureDevices":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"measureDevices","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)DotDevice","kind":"typeIdentifier","text":"DotDevice"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The measureing devices"}],"navigatorTitle":[{"kind":"identifier","text":"measureDevices"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/measureDevices","title":"measureDevices","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mdots\/measureviewcontroller\/measuredevices"},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController","navigatorTitle":[{"text":"MeasureViewController","kind":"identifier"}],"url":"\/documentation\/mdots\/measureviewcontroller","abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"MeasureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MeasureViewController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"measureDevices"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"measureDevices","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DotDevice *>"},{"text":" * ","kind":"text"},{"text":"measureDevices","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"measureDevices","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1measureDevices\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1measureDevices\/fragments","op":"replace","value":[{"text":"measureDevices","kind":"identifier"}]},{"op":"replace","value":"MeasureViewController","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MeasureViewController"}],"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/fragments"}]}]}