{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPatientID","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"patientId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setPatientID(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"setPatientID:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"MDots"}],"title":"setPatientID(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPatientID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)MeasureViewController(im)setPatientID:"},"variants":[{"paths":["\/documentation\/mdots\/measureviewcontroller\/setpatientid(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mdots\/measureviewcontroller\/setpatientid(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController"]]},"references":{"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController","navigatorTitle":[{"text":"MeasureViewController","kind":"identifier"}],"url":"\/documentation\/mdots\/measureviewcontroller","abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"MeasureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MeasureViewController"}]},"doc://com.estelapasjak.Mdots/documentation/MDots":{"type":"topic","url":"\/documentation\/mdots","title":"MDots","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","role":"collection"},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController/setPatientID(_:)":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController\/setPatientID(_:)","navigatorTitle":[{"kind":"identifier","text":"setPatientID:"}],"url":"\/documentation\/mdots\/measureviewcontroller\/setpatientid(_:)","abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"setPatientID(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPatientID"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setPatientID:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPatientID:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setPatientID:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"patientId","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/title","value":"MeasureViewController","op":"replace"},{"op":"replace","value":[{"text":"MeasureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/fragments"},{"value":"setPatientID:","op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setPatientID(_:)\/title"},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController~1setPatientID(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPatientID:","kind":"identifier"}],"op":"replace"}]}]}