{"metadata":{"externalID":"MDots","roleHeading":"Application","symbolKind":"module","title":"MDots","modules":[{"name":"MDots"}],"images":[{"type":"icon","identifier":"appIcon.png"}],"color":{"standardColorIdentifier":"orange"},"role":"collection"},"kind":"symbol","primaryContentSections":[{"kind":"content","content":[{"text":"Overview","anchor":"Overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The application is designed to assist users in managing and monitoring various physical movements using Movella DOT sensors. It provides functionalities for patient management and tracking, and real-time measurement and analysis of specific physical movements. The app is tailored for healthcare professionals, physiotherapists, and fitness trainers who need to measure and track the physical performance and rehabilitation progress of their patients.","type":"text"}]},{"level":2,"text":"Features","type":"heading","anchor":"Features"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Patient Management"}],"type":"strong"},{"type":"text","text":": Easily manage patient profiles and track their progress over time."}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Real-time Tracking","type":"text"}]},{"type":"text","text":": Monitor physical movements in real-time using Movella DOT sensors."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Data Analysis","type":"text"}]},{"text":": Analyze movement data to provide insights into patient performance and rehabilitation progress.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"heading","text":"Usage","level":2,"anchor":"Usage"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Setting Up"}],"type":"strong"},{"type":"text","text":": Install the application and set up your Movella DOT sensors."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Patient Profile Creation"}]},{"text":": Create profiles for each patient to manage their data.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Real-time Monitoring","type":"text"}]},{"text":": Start a session to monitor physical movements in real-time.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Data Review"}],"type":"strong"},{"text":": Analyze the collected data to assess patient progress and performance.","type":"text"}]}]}]},{"type":"heading","level":2,"text":"Screenshots","anchor":"Screenshots"},{"rows":[[[{"inlineContent":[{"identifier":"mockup2.png","type":"image"}],"type":"paragraph"}],[{"inlineContent":[{"identifier":"mockup1.png","type":"image"}],"type":"paragraph"}]],[[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Figure 1: Home Screen of the MDots App"}],"type":"emphasis"}],"type":"paragraph"}],[{"inlineContent":[{"type":"emphasis","inlineContent":[{"type":"text","text":"Figure 2: Patient Details Screen"}]}],"type":"paragraph"}]]],"type":"table","header":"row","alignments":["center","center"]}]}],"topicSections":[{"identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AddPatientViewModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthManager","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthViewModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/BridgingCoordinator","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/HomeViewModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/PatientDetailViewModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ProfileViewModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ResetViewModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SettingsViewModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SignInGoogleHelper","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SignInViewModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SignUpViewModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UpdateViewModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UserManager","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/Utilities"],"title":"Classes"},{"identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AddPatientView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthDataResultModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ChartView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ColorResource","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/DBUser","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/GifImage","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/GoogleSignInResultModel","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/HistoryView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/HomeView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ImageResource","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/LineChartData","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MDotsApp","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MovementData","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/Page","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/PageView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/Patient","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/PatientDetailView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ProfileView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ResetView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/RootView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SettingsView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SignInView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SignUpView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/StartView","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UpdateView"],"title":"Structures"},{"identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/convertToLineChartData(movementData:)","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/formatDouble(value:)","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/makeUIViewController()"],"title":"Functions"},{"identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthProviderOptions","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/LineChartType","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/TestType"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SwiftUI","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UIKit"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdots"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdots"]}],"identifier":{"url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"sections":[],"references":{"doc://com.estelapasjak.Mdots/documentation/MDots/CGPointThroughViewScale":{"abstract":[],"title":"CGPointThroughViewScale","role":"symbol","fragments":[{"kind":"identifier","text":"CGPointThroughViewScale"}],"type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGPointThroughViewScale","url":"\/documentation\/mdots\/cgpointthroughviewscale","kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/convertToLineChartData(movementData:)":{"abstract":[{"type":"text","text":"Converts MovementData array to LineChartData array."}],"title":"convertToLineChartData(movementData:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertToLineChartData"},{"text":"(","kind":"text"},{"text":"movementData","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:5MDots12MovementDataV","text":"MovementData","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"text":"LineChartData","kind":"typeIdentifier","preciseIdentifier":"s:5MDots13LineChartDataV"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/convertToLineChartData(movementData:)","kind":"symbol","url":"\/documentation\/mdots\/converttolinechartdata(movementdata:)"},"doc://com.estelapasjak.Mdots/documentation/MDots/AddPatientViewModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AddPatientViewModel","kind":"identifier"}],"title":"AddPatientViewModel","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"ViewModel for adding a new patient."}],"url":"\/documentation\/mdots\/addpatientviewmodel","role":"symbol","navigatorTitle":[{"text":"AddPatientViewModel","kind":"identifier"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AddPatientViewModel"},"doc://com.estelapasjak.Mdots/documentation/MDots/SwiftUI":{"title":"SwiftUI","kind":"symbol","type":"topic","url":"\/documentation\/mdots\/swiftui","abstract":[],"role":"collection","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SwiftUI"},"doc://com.estelapasjak.Mdots/documentation/MDots/CGSizeThroughViewScale":{"abstract":[],"title":"CGSizeThroughViewScale","role":"symbol","fragments":[{"text":"CGSizeThroughViewScale","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGSizeThroughViewScale","url":"\/documentation\/mdots\/cgsizethroughviewscale","kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/PatientDetailView":{"url":"\/documentation\/mdots\/patientdetailview","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A view that displays the details of a patient."}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/PatientDetailView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PatientDetailView"}],"title":"PatientDetailView","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PatientDetailView"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/SignInGoogleHelper":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SignInGoogleHelper","abstract":[{"type":"text","text":"A helper class for managing Google Sign-In operations."}],"url":"\/documentation\/mdots\/signingooglehelper","type":"topic","navigatorTitle":[{"text":"SignInGoogleHelper","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SignInGoogleHelper","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignInGoogleHelper"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/CGRectMakeFromSize":{"abstract":[],"title":"CGRectMakeFromSize","role":"symbol","fragments":[{"text":"CGRectMakeFromSize","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGRectMakeFromSize","kind":"symbol","url":"\/documentation\/mdots\/cgrectmakefromsize"},"doc://com.estelapasjak.Mdots/documentation/MDots/SettingsViewModel":{"title":"SettingsViewModel","abstract":[{"type":"text","text":"A view model class for managing settings-related functionality."}],"type":"topic","url":"\/documentation\/mdots\/settingsviewmodel","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SettingsViewModel"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SettingsViewModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsViewModel"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/RootView":{"navigatorTitle":[{"kind":"identifier","text":"RootView"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RootView","kind":"identifier"}],"title":"RootView","kind":"symbol","type":"topic","abstract":[{"text":"Represents the root view of the MDots application.","type":"text"}],"url":"\/documentation\/mdots\/rootview","role":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/RootView"},"doc://com.estelapasjak.Mdots/documentation/MDots/UIViewAutoresizingAdditional":{"abstract":[],"fragments":[{"text":"UIViewAutoresizingAdditional","kind":"identifier"}],"url":"\/documentation\/mdots\/uiviewautoresizingadditional","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UIViewAutoresizingAdditional","title":"UIViewAutoresizingAdditional","kind":"symbol","role":"symbol","type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/HomeView":{"type":"topic","title":"HomeView","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/HomeView","url":"\/documentation\/mdots\/homeview","abstract":[{"type":"text","text":"View representing the home screen of the application."}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HomeView"}],"navigatorTitle":[{"kind":"identifier","text":"HomeView"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/PageView":{"role":"symbol","url":"\/documentation\/mdots\/pageview","type":"topic","navigatorTitle":[{"text":"PageView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageView"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/PageView","title":"PageView","kind":"symbol","abstract":[{"type":"text","text":"A view that displays a single page with an image and a description."}]},"doc://com.estelapasjak.Mdots/documentation/MDots/UIStatusBarHeightCommon":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"UIStatusBarHeightCommon","kind":"identifier"}],"title":"UIStatusBarHeightCommon","url":"\/documentation\/mdots\/uistatusbarheightcommon","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UIStatusBarHeightCommon","abstract":[]},"doc://com.estelapasjak.Mdots/documentation/MDots/makeUIViewController()":{"abstract":[{"type":"text","text":"Function to create the main UIViewController."}],"kind":"symbol","url":"\/documentation\/mdots\/makeuiviewcontroller()","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/makeUIViewController()","type":"topic","title":"makeUIViewController()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"makeUIViewController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MainViewController","text":"MainViewController","kind":"typeIdentifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthError":{"title":"AuthError","url":"\/documentation\/mdots\/autherror","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthError","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AuthError"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthError","type":"topic","abstract":[{"type":"text","text":"An enumeration representing various authentication errors that can occur."}]},"doc://com.estelapasjak.Mdots/documentation/MDots/MovementData":{"title":"MovementData","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MovementData","kind":"identifier"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MovementData","navigatorTitle":[{"text":"MovementData","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Model for Movement Data.","type":"text"}],"url":"\/documentation\/mdots\/movementdata","role":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/UIKit":{"url":"\/documentation\/mdots\/uikit","role":"collection","kind":"symbol","abstract":[],"title":"UIKit","type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UIKit"},"doc://com.estelapasjak.Mdots/documentation/MDots/DeviceMeasureCell":{"abstract":[],"title":"DeviceMeasureCell","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/DeviceMeasureCell","role":"symbol","url":"\/documentation\/mdots\/devicemeasurecell","kind":"symbol","fragments":[{"text":"DeviceMeasureCell","kind":"identifier"}],"type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/ProfileViewModel":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ProfileViewModel","kind":"identifier"}],"title":"ProfileViewModel","kind":"symbol","type":"topic","abstract":[{"text":"A view model for managing the user’s profile information.","type":"text"}],"url":"\/documentation\/mdots\/profileviewmodel","role":"symbol","navigatorTitle":[{"text":"ProfileViewModel","kind":"identifier"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ProfileViewModel"},"doc://com.estelapasjak.Mdots/documentation/MDots/HomeViewModel":{"navigatorTitle":[{"kind":"identifier","text":"HomeViewModel"}],"abstract":[{"type":"text","text":"Manages the data and functionality for the home view."}],"type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/HomeViewModel","url":"\/documentation\/mdots\/homeviewmodel","kind":"symbol","title":"HomeViewModel","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HomeViewModel"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/Utilities":{"abstract":[{"text":"A singleton class providing utility functions for the application.","type":"text"}],"title":"Utilities","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Utilities","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Utilities","kind":"identifier"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/Utilities","url":"\/documentation\/mdots\/utilities","kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/MDotsApp":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDotsApp","kind":"identifier"}],"navigatorTitle":[{"text":"MDotsApp","kind":"identifier"}],"role":"symbol","title":"MDotsApp","kind":"symbol","url":"\/documentation\/mdots\/mdotsapp","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MDotsApp","type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController","title":"MainViewController","role":"symbol","url":"\/documentation\/mdots\/mainviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainViewController"}],"navigatorTitle":[{"kind":"identifier","text":"MainViewController"}],"type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/BridgingCoordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BridgingCoordinator","kind":"identifier"}],"title":"BridgingCoordinator","kind":"symbol","type":"topic","url":"\/documentation\/mdots\/bridgingcoordinator","abstract":[{"type":"text","text":"The bridging coordinator to manage communication with UIKit."}],"role":"symbol","navigatorTitle":[{"text":"BridgingCoordinator","kind":"identifier"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/BridgingCoordinator"},"doc://com.estelapasjak.Mdots/documentation/MDots/ImageResource":{"url":"\/documentation\/mdots\/imageresource","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An image resource."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageResource"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ImageResource","title":"ImageResource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageResource"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/TestType":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/TestType","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TestType","kind":"identifier"}],"url":"\/documentation\/mdots\/testtype","abstract":[{"text":"An enumeration representing different types of tests.","type":"text"}],"type":"topic","title":"TestType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TestType","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/UpdateView":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UpdateView","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mdots\/updateview","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UpdateView","abstract":[{"type":"text","text":"View for updating user information."}],"type":"topic","title":"UpdateView","navigatorTitle":[{"kind":"identifier","text":"UpdateView"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthDataResultModel":{"url":"\/documentation\/mdots\/authdataresultmodel","kind":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthDataResultModel","role":"symbol","title":"AuthDataResultModel","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthDataResultModel"}],"navigatorTitle":[{"text":"AuthDataResultModel","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A model representing the authentication result data."}]},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthView":{"title":"AuthView","role":"symbol","url":"\/documentation\/mdots\/authview","kind":"symbol","abstract":[{"type":"text","text":"A view for handling authentication methods."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthView"}],"navigatorTitle":[{"text":"AuthView","kind":"identifier"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthView","type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/SignInViewModel":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInViewModel","kind":"identifier"}],"url":"\/documentation\/mdots\/signinviewmodel","title":"SignInViewModel","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SignInViewModel","kind":"symbol","abstract":[{"type":"text","text":"View model for sign-in functionality."}],"navigatorTitle":[{"text":"SignInViewModel","kind":"identifier"}],"type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/DeviceConnectCell":{"title":"DeviceConnectCell","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"DeviceConnectCell","kind":"identifier"}],"url":"\/documentation\/mdots\/deviceconnectcell","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/DeviceConnectCell","type":"topic"},"appIcon.png":{"identifier":"appIcon.png","alt":"The logo representing the MDot sensor application.","type":"image","variants":[{"url":"\/images\/appIcon.png","traits":["1x","light"]}]},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthViewModel":{"abstract":[{"text":"A view model for handling authentication-related operations.","type":"text"}],"kind":"symbol","role":"symbol","title":"AuthViewModel","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthViewModel","type":"topic","navigatorTitle":[{"text":"AuthViewModel","kind":"identifier"}],"url":"\/documentation\/mdots\/authviewmodel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthViewModel","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/ResetView":{"url":"\/documentation\/mdots\/resetview","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A view for resetting the password."}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ResetView","type":"topic","navigatorTitle":[{"text":"ResetView","kind":"identifier"}],"title":"ResetView","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResetView"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/UpdateViewModel":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UpdateViewModel","kind":"identifier"}],"url":"\/documentation\/mdots\/updateviewmodel","abstract":[{"text":"ViewModel for updating user credentials.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"UpdateViewModel","kind":"identifier"}],"title":"UpdateViewModel","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UpdateViewModel"},"doc://com.estelapasjak.Mdots/documentation/MDots/UIHomeIndicatorHeightForIPhoneX":{"abstract":[],"title":"UIHomeIndicatorHeightForIPhoneX","role":"symbol","fragments":[{"text":"UIHomeIndicatorHeightForIPhoneX","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UIHomeIndicatorHeightForIPhoneX","url":"\/documentation\/mdots\/uihomeindicatorheightforiphonex","kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/LineChartData":{"title":"LineChartData","url":"\/documentation\/mdots\/linechartdata","abstract":[{"type":"text","text":"Struct representing data for a line chart."}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineChartData"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/LineChartData","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LineChartData"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/LineChartType":{"title":"LineChartType","url":"\/documentation\/mdots\/linecharttype","abstract":[{"type":"text","text":"Enum representing different types of line charts."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LineChartType"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/LineChartType","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"LineChartType","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/ColorResource":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ColorResource","kind":"identifier"}],"abstract":[{"text":"A color resource.","type":"text"}],"navigatorTitle":[{"text":"ColorResource","kind":"identifier"}],"title":"ColorResource","url":"\/documentation\/mdots\/colorresource","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ColorResource"},"doc://com.estelapasjak.Mdots/documentation/MDots/CGSizeMaxSpaceSize":{"abstract":[],"title":"CGSizeMaxSpaceSize","role":"symbol","fragments":[{"text":"CGSizeMaxSpaceSize","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGSizeMaxSpaceSize","url":"\/documentation\/mdots\/cgsizemaxspacesize","kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/UIStatusBarHeightForIPhoneX":{"abstract":[],"kind":"symbol","role":"symbol","title":"UIStatusBarHeightForIPhoneX","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UIStatusBarHeightForIPhoneX","type":"topic","url":"\/documentation\/mdots\/uistatusbarheightforiphonex","fragments":[{"text":"UIStatusBarHeightForIPhoneX","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/GifImage":{"title":"GifImage","url":"\/documentation\/mdots\/gifimage","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/GifImage","type":"topic","abstract":[{"type":"text","text":"A view that displays a GIF image using a "},{"type":"codeVoice","code":"WKWebView"},{"text":".","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"GifImage","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GifImage"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/SignUpView":{"kind":"symbol","url":"\/documentation\/mdots\/signupview","navigatorTitle":[{"text":"SignUpView","kind":"identifier"}],"title":"SignUpView","role":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SignUpView","abstract":[{"type":"text","text":"View for signing up with email."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SignUpView","kind":"identifier"}],"type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/ResetViewModel":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResetViewModel"}],"url":"\/documentation\/mdots\/resetviewmodel","abstract":[{"type":"text","text":"View model for handling password reset functionality."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ResetViewModel","kind":"identifier"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ResetViewModel","title":"ResetViewModel"},"doc://com.estelapasjak.Mdots/documentation/MDots/SettingsView":{"abstract":[{"text":"A view for managing user settings, including credentials updates, sign-out, and account deletion.","type":"text"}],"title":"SettingsView","type":"topic","url":"\/documentation\/mdots\/settingsview","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SettingsView","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SettingsView","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SettingsView","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/MeasureViewController":{"role":"symbol","url":"\/documentation\/mdots\/measureviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MeasureViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MeasureViewController","kind":"identifier"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController","title":"MeasureViewController","abstract":[],"kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/DBUser":{"type":"topic","abstract":[{"type":"text","text":"A model representing a user in the database."}],"url":"\/documentation\/mdots\/dbuser","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DBUser","kind":"identifier"}],"kind":"symbol","title":"DBUser","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/DBUser","role":"symbol","navigatorTitle":[{"text":"DBUser","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/UINavigationBarHeight":{"kind":"symbol","abstract":[],"role":"symbol","title":"UINavigationBarHeight","type":"topic","url":"\/documentation\/mdots\/uinavigationbarheight","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UINavigationBarHeight","fragments":[{"text":"UINavigationBarHeight","kind":"identifier"}]},"mockup2.png":{"type":"image","variants":[{"url":"\/images\/mockup2.png","traits":["1x","light"]}],"identifier":"mockup2.png","alt":"App Mockup 1"},"mockup1.png":{"variants":[{"url":"\/images\/mockup1.png","traits":["1x","light"]}],"alt":"App Mockup 2","type":"image","identifier":"mockup1.png"},"doc://com.estelapasjak.Mdots/documentation/MDots/UserManager":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UserManager","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UserManager","kind":"identifier"}],"url":"\/documentation\/mdots\/usermanager","abstract":[{"type":"text","text":"A singleton class for managing user data in Firestore."}],"type":"topic","title":"UserManager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserManager"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/Patient":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/Patient","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Patient"}],"type":"topic","title":"Patient","abstract":[{"type":"text","text":"Represents a patient with various attributes."}],"url":"\/documentation\/mdots\/patient","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Patient","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/ProfileView":{"abstract":[{"text":"A view that displays the user’s profile information.","type":"text"}],"title":"ProfileView","type":"topic","url":"\/documentation\/mdots\/profileview","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ProfileView","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ProfileView","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ProfileView","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/formatDouble(value:)":{"kind":"symbol","abstract":[{"text":"Formats a double value to a string with two decimal places.","type":"text"}],"role":"symbol","title":"formatDouble(value:)","type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/formatDouble(value:)","url":"\/documentation\/mdots\/formatdouble(value:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formatDouble","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/Page":{"abstract":[{"type":"text","text":"Represents a page in the measurement setup values."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Page","kind":"identifier"}],"url":"\/documentation\/mdots\/page","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/Page","navigatorTitle":[{"kind":"identifier","text":"Page"}],"title":"Page","kind":"symbol","role":"symbol","type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/SignInView":{"navigatorTitle":[{"text":"SignInView","kind":"identifier"}],"abstract":[{"type":"text","text":"A view for signing in."}],"type":"topic","kind":"symbol","url":"\/documentation\/mdots\/signinview","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SignInView","title":"SignInView","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SignInView","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/PatientDetailViewModel":{"kind":"symbol","url":"\/documentation\/mdots\/patientdetailviewmodel","navigatorTitle":[{"kind":"identifier","text":"PatientDetailViewModel"}],"title":"PatientDetailViewModel","role":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/PatientDetailViewModel","abstract":[{"text":"ViewModel for adding a new patient.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PatientDetailViewModel"}],"type":"topic"},"doc://com.estelapasjak.Mdots/documentation/MDots/GoogleSignInResultModel":{"navigatorTitle":[{"text":"GoogleSignInResultModel","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GoogleSignInResultModel","kind":"identifier"}],"title":"GoogleSignInResultModel","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/GoogleSignInResultModel","type":"topic","url":"\/documentation\/mdots\/googlesigninresultmodel","role":"symbol","abstract":[{"type":"text","text":"A model representing the result of a Google Sign-In operation."}],"kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/AddPatientView":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AddPatientView"}],"title":"AddPatientView","abstract":[{"text":"A view for adding a new patient’s information.","type":"text"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AddPatientView","type":"topic","kind":"symbol","url":"\/documentation\/mdots\/addpatientview","navigatorTitle":[{"kind":"identifier","text":"AddPatientView"}]},"doc://com.estelapasjak.Mdots/documentation/MDots":{"type":"topic","role":"collection","url":"\/documentation\/mdots","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","abstract":[],"images":[{"identifier":"appIcon.png","type":"icon"}],"kind":"symbol","title":"MDots"},"doc://com.estelapasjak.Mdots/documentation/MDots/ChartView":{"title":"ChartView","navigatorTitle":[{"kind":"identifier","text":"ChartView"}],"type":"topic","abstract":[{"type":"text","text":"View representing the chart."}],"url":"\/documentation\/mdots\/chartview","role":"symbol","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/ChartView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChartView","kind":"identifier"}],"kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthProviderOptions":{"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthProviderOptions","url":"\/documentation\/mdots\/authprovideroptions","abstract":[{"type":"text","text":"Enum representing the different authentication provider options."}],"title":"AuthProviderOptions","navigatorTitle":[{"kind":"identifier","text":"AuthProviderOptions"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthProviderOptions","kind":"identifier"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/SignUpViewModel":{"kind":"symbol","abstract":[{"type":"text","text":"View model for sign-up functionality."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SignUpViewModel","kind":"identifier"}],"title":"SignUpViewModel","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/SignUpViewModel","url":"\/documentation\/mdots\/signupviewmodel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignUpViewModel"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/AuthManager":{"navigatorTitle":[{"text":"AuthManager","kind":"identifier"}],"url":"\/documentation\/mdots\/authmanager","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthManager","kind":"identifier"}],"title":"AuthManager","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/AuthManager","abstract":[{"type":"text","text":"A singleton class for managing authentication using Firebase."}],"role":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/HistoryView":{"title":"HistoryView","type":"topic","abstract":[{"text":"View for displaying and managing a patient’s movement data history.","type":"text"}],"url":"\/documentation\/mdots\/historyview","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/HistoryView","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"HistoryView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HistoryView"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/CGRectThroughViewScale":{"kind":"symbol","abstract":[],"role":"symbol","title":"CGRectThroughViewScale","url":"\/documentation\/mdots\/cgrectthroughviewscale","type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGRectThroughViewScale","fragments":[{"kind":"identifier","text":"CGRectThroughViewScale"}]},"doc://com.estelapasjak.Mdots/documentation/MDots/CGFloatThroughViewScale":{"abstract":[],"title":"CGFloatThroughViewScale","role":"symbol","fragments":[{"kind":"identifier","text":"CGFloatThroughViewScale"}],"type":"topic","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGFloatThroughViewScale","url":"\/documentation\/mdots\/cgfloatthroughviewscale","kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/StartView":{"abstract":[{"type":"text","text":"View for the start screen of the MDots app."}],"role":"symbol","type":"topic","url":"\/documentation\/mdots\/startview","navigatorTitle":[{"text":"StartView","kind":"identifier"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/StartView","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartView"}],"title":"StartView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/DeviceConnectCell","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/DeviceMeasureCell","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MeasureViewController"],"title":"Classes"},{"title":"Variables","identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UIHomeIndicatorHeightForIPhoneX","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UINavigationBarHeight","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UIStatusBarHeightCommon","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UIStatusBarHeightForIPhoneX"]},{"identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGFloatThroughViewScale","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGPointThroughViewScale","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGRectMakeFromSize","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGRectThroughViewScale","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGSizeMaxSpaceSize","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/CGSizeThroughViewScale"],"title":"Functions"},{"title":"Enumerations","identifiers":["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/UIViewAutoresizingAdditional"]}],"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController\/title","value":"MainViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController\/fragments","value":[{"kind":"identifier","text":"MainViewController"}]},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/title","op":"replace","value":"MeasureViewController"},{"path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MeasureViewController\/fragments","op":"replace","value":[{"text":"MeasureViewController","kind":"identifier"}]}]}]}