{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mdots\/mainviewcontroller\/settesttype(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mdots\/mainviewcontroller\/settesttype(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTestType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"testtype"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setTestType(_:)"},"metadata":{"modules":[{"name":"MDots"}],"title":"setTestType(_:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"setTestType:","kind":"identifier"}],"symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTestType"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)MainViewController(im)setTestType:"},"hierarchy":{"paths":[["doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots","doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController"]]},"kind":"symbol","references":{"doc://com.estelapasjak.Mdots/documentation/MDots":{"kind":"symbol","role":"collection","title":"MDots","url":"\/documentation\/mdots","type":"topic","abstract":[],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots"},"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController/setTestType(_:)":{"title":"setTestType(_:)","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTestType","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setTestType:"}],"identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController\/setTestType(_:)","type":"topic","url":"\/documentation\/mdots\/mainviewcontroller\/settesttype(_:)","kind":"symbol"},"doc://com.estelapasjak.Mdots/documentation/MDots/MainViewController":{"title":"MainViewController","identifier":"doc:\/\/com.estelapasjak.Mdots\/documentation\/MDots\/MainViewController","navigatorTitle":[{"text":"MainViewController","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MainViewController","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/mdots\/mainviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"setTestType:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTestType:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setTestType:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"testtype","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"setTestType:","op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setTestType(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setTestType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController~1setTestType(_:)\/fragments"},{"op":"replace","value":"MainViewController","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.estelapasjak.Mdots~1documentation~1MDots~1MainViewController\/fragments","value":[{"text":"MainViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}